language: clojure

# Don't use the Travis Container-Based Infrastructure
sudo: true

addons:
    chrome: stable

before_script:
    # compile builtin sources with LATEST planck
    # - sudo add-apt-repository -y ppa:mfikes/planck
    # - sudo apt-get update -q
    # - sudo apt-get install -y planck
    #
    - sudo apt-get install javascriptcoregtk-3.0 libglib2.0-dev libzip-dev libcurl4-gnutls-dev libicu-dev
    - git clone --depth 1 https://github.com/planck-repl/planck.git
    - (cd planck && script/build && script/install)
    - planck --version

    # plk depends on clojure
    - curl -O https://download.clojure.org/install/linux-install-1.9.0.381.sh
    - chmod +x linux-install-1.9.0.381.sh
    - sudo ./linux-install-1.9.0.381.sh

    # set up the plk tool
    - export PATH=$PATH:$PWD/planck/planck-sh/

script:
    - lein test
    - scripts/compile-builtin-sources

after_success:
    - lein do clean, cljsbuild once min, less once

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_DEPLOY # Set in travis-ci.org dashboard
    local_dir: resources/public
    on:
        branch: master


